backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "content"
    label: "Portfolio Content"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "homepage"
        fields:
          - { label: "About", name: "about", widget: "text" }
          - { label: "Projects", name: "projects", widget: "text" }
          - { label: "Contact", name: "contact", widget: "text" }
